### ISSUE TITLE
Can you explain how to convert the parsed structure to different format

### ISSUE THREAD

**Issue by kmrsh** [uds-se/FormatFuzzer#10]
## Converted to JSON

This is really nice and fast C++ tool for parsing 010 template based binaries. However we need to convert parsed data structure to JSON or XML, Could you guide on where we can implement such thing or what existing functionalities that can be used to do this easily.

I tried the FormatFuzzer with our own template and it seems it can parse the binaries based on the output it generates, But we want this to generate the JSON output from the tree.

Thank you

**Comment by kmrsh** [comment]
To add to the above,

I found the `parse` option doesn't allow files larger than 4096 bytes due to `MAX_FILE_SIZE`. I then modified it to a larger value in order to parse 1MB file, but once it parsed 1000 or records, it is giving me the below error.
~~~
Error: random size exceeded rand_size
~~~

I then extract the records where it gives the error into a separate file and tried again then it was successful.  So it seems it is due to file size again. Any idea how to fix this so that it can easily parse 1-2MB file. My plan was to use it then to generate json output

**Comment by RafaelTupynamba** [comment]
Hello,
To parse large files, you'll have to increase both MAX_FILE_SIZE and MAX_RAND_SIZE.
The output (parse tree of the file) is printed here:
https://github.com/uds-se/FormatFuzzer/blob/1bdf07b9d97389f7f5db6dc7fff48e29f84225d3/bt.h#L220
We print the byte range (start and end byte positions), followed by the full branch of the parse tree (from the root to the current node).
We also print information on whether the chunk is appendable or optional (this is relevant if you want to perform smart mutations).
You could change this function to output the information in JSON or XML or other format.
