### ISSUE TITLE
Automatic delete file and control max width and height image file

### ISSUE THREAD

**Issue by CityOfLight77** [uds-se/FormatFuzzer#12]
I would like to have a flag to automatically delete error file when running `./gif-fuzzer parse input.gif`
And I want to control max width and height when generating images using `./gif-fuzzer fuzz` command

**Comment by RafaelTupynamba** [comment]
Do you want to delete the file `input.gif` if parsing fails? You could write a script to do that in some scripting language or a simple shell command:
`./gif-fuzzer parse input.gif || rm input.gif`
This would remove the file if the parse command returns failure.
To set a max width and height, just edit the binary template `templates/gif.bt`
`	ushort	Width <max=32>;`
`	ushort	Height <max=32>;`
`				ushort	ImageWidth <max=32>;`
`				ushort	ImageHeight <max=32>;`
