### ISSUE TITLE
Fatal error: 'boost/crc.hpp' file not found

### ISSUE THREAD

**Issue by andreas-zeller** [uds-se/FormatFuzzer#13]
After creating the issue, checkboxes will appear where `[] label` exist in the
markdown. You can check/uncheck them to fill out the environment section.

## Checklist

- [x] I have filled out the environment section

## Environment

**Platform** 

- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] Other (please specify)

**Python Version**

- [ ] Python 2.7
- [ ] Python 3.4
- [ ] Python 3.5
- [ ] Python 3.6
- [ ] Python 3.7
- [x] Python 3.8
- [ ] Other (please specify)

## Describe the bug

After checking out FormatFuzzer, I get

```sh
$ make gif-fuzzer
g++ -std=c++17 -DHAVE_CONFIG_H -I.     -g -O3 -Wall -MT gif.o -MD -MP -MF .deps/gif.Tpo -c -o gif.o gif.cpp
In file included from gif.cpp:6:
./bt.h:12:10: fatal error: 'boost/crc.hpp' file not found
#include <boost/crc.hpp>
         ^~~~~~~~~~~~~~~
```

## To Reproduce

See above

## Expected Behavior

`gif-fuzzer` should be produced

**Comment by RafaelTupynamba** [comment]
Oh, I added a prerequisite to install boost so we can support more checksums algorithms (CRC32, CRC16, etc.), as required by some formats (such as MP3).
The README.md already gives some instructions to install boost.
Can you check if it works with `brew install boost`?

**Comment by andreas-zeller** [comment]
Ok, after installing `boost`, things work just fine!
