### ISSUE TITLE
Have a “mutate” command

### ISSUE THREAD

**Issue by andreas-zeller** [uds-se/FormatFuzzer#2]
“mutate file1 file2” would parse file1, invert one randomly chosen decision, and then generate file2.  Simple, yet effective.

**Comment by RafaelTupynamba** [comment]
Mutate commands already implemented:
replace    - Apply a smart replacement
delete     - Apply a smart deletion
insert     - Apply a smart insertion
abstract   - Apply a smart abstraction
swap       - Apply a smart swap
mutations  - Smart mutations
