### ISSUE TITLE
generate_buffer()?

### ISSUE THREAD

**Issue by Manouchehri** [uds-se/FormatFuzzer#5]
First of all, thanks for the project! Looks interesting, hoping to add it to my workflow tomorrow.

Is there an easy way to implement something that works similar to generate_file(), except using buffers instead of using file descriptors?

I tried copying `afl_pre_save_handler`, but it looks like that expects stdin? 

```c++
extern "C" size_t afl_pre_save_handler(unsigned char *data, size_t size,
                                       unsigned char **new_data) {
  file_acc.seed(data, size, 0);
  try {
    generate_file();
  } catch (...) {
    delete_globals();
    *new_data = NULL;
    return 0;
  }
  *new_data = file_acc.file_buffer;
  return file_acc.file_size;
}
```

**Comment by RafaelTupynamba** [comment]
`afl_pre_save_handler()` is exactly what you need.
It takes a buffer `data` of size `size` as input representing the random bytes used to make decisions during generation.
It generates the file in variable `new_data` and returns its size.

**Comment by Manouchehri** [comment]
Oh, thanks! To clarify, is `data` the same as the decision file generated by `--decisions`?

Currently I end up getting `Error: random size exceeded rand_size` when trying to use FormatFuzzer with my fuzzer. Any idea what might be going wrong?

**Comment by Manouchehri** [comment]
Ah, so the issue seems to be when mutating the decision files. I basically end up producing invalid files, which causes the failure.
