### ISSUE TITLE
Limiting to range?

### ISSUE THREAD

**Issue by Manouchehri** [uds-se/FormatFuzzer#9]
Currently writing a new template that needs to seek to an offset that's defined in the file itself. The issue is that because I try to use `FSeek` to an invalid offset often, the vast majority of files end up being invalid. It's extremely slow.

```
dave@ubuntu:/mnt/space/FormatFuzzer$ ./dave-fuzzer benchmark
Generated 7 files from 10000 attempts in 1.245248 s.
Average file size 285 bytes.
Speed 5.621370 / s.
```

And my template looks like this:
```
uint32 off;
FSeek(off);
```

Any suggestions on how I can give FormatFuzzer a hint that `off` can't be larger than the file itself?

**Comment by RafaelTupynamba** [comment]
By default, for integer types (such as uint32) we give preference to generating small values. If you add the arraylength metadata to the variable, the preference will be even stronger and should almost always generate values from 1 to 16.
`uint32 off<arraylength=true>;`
What is the most common error message that you see when running `./dave-fuzzer test`?
If the files you're generating keep exceeding `MAX_FILE_SIZE` you could also increase `MAX_FILE_SIZE` to the appropriate value.

**Comment by Manouchehri** [comment]
Thanks, I changed that, though I still often get this:

```
Error: FSeek/FSkip: invalid position
```

Still slow. =( 
```
Generated 9 files from 10000 attempts in 1.553938 s.
Average file size 158 bytes.
Speed 5.791737 / s.
```


```
uint32 off<format=hex,arraylength=true>;
```
^ I have ten of these in my format, not just one. How does the "preference" work? e.g. if each `off` has a 20% chance of being >16, then that's still going to be a large value the majority of the time on at least one instance.

**Comment by Manouchehri** [comment]
It would be much better if I could set `off <= FileSize()`.

**Comment by RafaelTupynamba** [comment]
We also have min and max metadata options. You could write something like
`uint32 off <min=0,max=1024>;`
We currently only support numerical constants here.

You can also disable evil decisions to remove the 1% chance of choosing a value outside the range [min, max]:
`local int evil = SetEvilBit(false);`
`uint32 off <min=0,max=1024>;`
`SetEvilBit(evil);`

If you want to force the file size to be some particular value during generation, you could add this to the beginning of the template:We also have min and max metadata options. You could write something like
`FSeek(1024);`
`FEof(1.0);`
`FSeek(0);`
This would jump to position 1024, call FEof() with a probability 1.0 of returning "true" which means the file terminates there, and finally jumping back to the beginning.
